### ISSUE TITLE
Python 3.6 problem: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by matidio** [lukas-schulze/keepass2xml-solve-references#1]
Running your script with python version 3.6.6 I get the following error:

```
Traceback (most recent call last):
  File "C:/Working/solve-references.py", line 146, in <module>
    ref_base64 = convert_uuid_to_base64(ref_hex)
  File "C:/Working/solve-references.py", line 25, in convert_uuid_to_base64
    return value.decode('hex') .encode('base64')
AttributeError: 'str' object has no attribute 'decode'
```
I suppose it's a compatibility problem of python versions. As I'm not an expert in python maybe you could help me to resolve this problem?

Thank you very much

**Comment by schulluk** [comment]
Unfortunately, I need more information.
I updated the script and created a separate branch for it.
You can find the updated file here:
https://github.com/lsgd/keepass2xml-solve-references/blob/fix-decode-encode-python3/solve-references.py
You can also see the changes I made here: https://github.com/lsgd/keepass2xml-solve-references/commit/b67d408f9c20e59aa88d0428b4081107b01b1818#diff-880f130bfa24c4c5fe1b33bedfdf7da9

In case of this error, the script will add additional output for:
1. the type of the value variable
2. the content of the value variable

Since the content of the value variable is a unique ID and is not related to your password or stored information in any way, you can safely share this information with me.

As soon as I get those 2 information from you, I can start fixing the script.

**Comment by matidio** [comment]
At home I use another environment but it shouldn't make any difference.
Below you'll find the output of your modified version
As I understood reading some Stackoverflow answers (I looked for "str
object has no attribute decode hex") it seems a problem with python
versions > 3.4.4.
Unfortunately I've no experience with Python so my experiments to resolve
the problem failed miserably

I didn't mentioned the export format: Keepass2 Standard XML
I hope the information below can help you to find a fix

Let me know if you need further information

Thanks in advance
Matidio

---

python3.6 solve-references.py Standard.xml

Type: <class 'str'>
Value: A12B489C9B679546A8D5B24A1AAB55D8
'str' object has no attribute 'decode'

**Comment by schulluk** [comment]
I updated the script. Please download it from here: https://github.com/lsgd/keepass2xml-solve-references/blob/fix-decode-encode-python3/solve-references.py

Please give me some feedback if this works for you, so I can make it available for everyone.
Thank you.

**Comment by matidio** [comment]
Hi,

the scripts seems to work fine. The decoding error is vanished.

Thank you very much for your effort to solve this problem.

Have a nice day
Matidio

**Comment by schulluk** [comment]
Thank you for notifying me.
I added the changes to the master branch which means it's now available for everyone.
